package com.example.borderly

import java.util.Locale

internal data class IsoCountryCode(
    val alpha2: String,
    val alpha3: String
)

/**
 * ISO 3166 search aliases for every real Borderly destination.
 * Kosovo uses the commonly used XK / XKX aliases because ISO 3166 has not
 * assigned it an official alpha code; Borderly already uses numeric id 983.
 */
internal val IsoCountryCodesByNumeric: Map<Int, IsoCountryCode> = mapOf(
    4 to IsoCountryCode("AF", "AFG"),
    8 to IsoCountryCode("AL", "ALB"),
    12 to IsoCountryCode("DZ", "DZA"),
    16 to IsoCountryCode("AS", "ASM"),
    20 to IsoCountryCode("AD", "AND"),
    24 to IsoCountryCode("AO", "AGO"),
    28 to IsoCountryCode("AG", "ATG"),
    31 to IsoCountryCode("AZ", "AZE"),
    32 to IsoCountryCode("AR", "ARG"),
    36 to IsoCountryCode("AU", "AUS"),
    40 to IsoCountryCode("AT", "AUT"),
    44 to IsoCountryCode("BS", "BHS"),
    48 to IsoCountryCode("BH", "BHR"),
    50 to IsoCountryCode("BD", "BGD"),
    51 to IsoCountryCode("AM", "ARM"),
    52 to IsoCountryCode("BB", "BRB"),
    56 to IsoCountryCode("BE", "BEL"),
    60 to IsoCountryCode("BM", "BMU"),
    64 to IsoCountryCode("BT", "BTN"),
    68 to IsoCountryCode("BO", "BOL"),
    70 to IsoCountryCode("BA", "BIH"),
    72 to IsoCountryCode("BW", "BWA"),
    76 to IsoCountryCode("BR", "BRA"),
    84 to IsoCountryCode("BZ", "BLZ"),
    86 to IsoCountryCode("IO", "IOT"),
    90 to IsoCountryCode("SB", "SLB"),
    92 to IsoCountryCode("VG", "VGB"),
    96 to IsoCountryCode("BN", "BRN"),
    100 to IsoCountryCode("BG", "BGR"),
    104 to IsoCountryCode("MM", "MMR"),
    108 to IsoCountryCode("BI", "BDI"),
    112 to IsoCountryCode("BY", "BLR"),
    116 to IsoCountryCode("KH", "KHM"),
    120 to IsoCountryCode("CM", "CMR"),
    124 to IsoCountryCode("CA", "CAN"),
    132 to IsoCountryCode("CV", "CPV"),
    136 to IsoCountryCode("KY", "CYM"),
    140 to IsoCountryCode("CF", "CAF"),
    144 to IsoCountryCode("LK", "LKA"),
    148 to IsoCountryCode("TD", "TCD"),
    152 to IsoCountryCode("CL", "CHL"),
    156 to IsoCountryCode("CN", "CHN"),
    158 to IsoCountryCode("TW", "TWN"),
    162 to IsoCountryCode("CX", "CXR"),
    166 to IsoCountryCode("CC", "CCK"),
    170 to IsoCountryCode("CO", "COL"),
    174 to IsoCountryCode("KM", "COM"),
    175 to IsoCountryCode("YT", "MYT"),
    178 to IsoCountryCode("CG", "COG"),
    180 to IsoCountryCode("CD", "COD"),
    184 to IsoCountryCode("CK", "COK"),
    188 to IsoCountryCode("CR", "CRI"),
    191 to IsoCountryCode("HR", "HRV"),
    192 to IsoCountryCode("CU", "CUB"),
    196 to IsoCountryCode("CY", "CYP"),
    203 to IsoCountryCode("CZ", "CZE"),
    204 to IsoCountryCode("BJ", "BEN"),
    208 to IsoCountryCode("DK", "DNK"),
    212 to IsoCountryCode("DM", "DMA"),
    214 to IsoCountryCode("DO", "DOM"),
    218 to IsoCountryCode("EC", "ECU"),
    222 to IsoCountryCode("SV", "SLV"),
    226 to IsoCountryCode("GQ", "GNQ"),
    231 to IsoCountryCode("ET", "ETH"),
    232 to IsoCountryCode("ER", "ERI"),
    233 to IsoCountryCode("EE", "EST"),
    234 to IsoCountryCode("FO", "FRO"),
    238 to IsoCountryCode("FK", "FLK"),
    239 to IsoCountryCode("GS", "SGS"),
    242 to IsoCountryCode("FJ", "FJI"),
    246 to IsoCountryCode("FI", "FIN"),
    248 to IsoCountryCode("AX", "ALA"),
    250 to IsoCountryCode("FR", "FRA"),
    254 to IsoCountryCode("GF", "GUF"),
    258 to IsoCountryCode("PF", "PYF"),
    260 to IsoCountryCode("TF", "ATF"),
    262 to IsoCountryCode("DJ", "DJI"),
    266 to IsoCountryCode("GA", "GAB"),
    268 to IsoCountryCode("GE", "GEO"),
    270 to IsoCountryCode("GM", "GMB"),
    275 to IsoCountryCode("PS", "PSE"),
    276 to IsoCountryCode("DE", "DEU"),
    288 to IsoCountryCode("GH", "GHA"),
    292 to IsoCountryCode("GI", "GIB"),
    296 to IsoCountryCode("KI", "KIR"),
    300 to IsoCountryCode("GR", "GRC"),
    304 to IsoCountryCode("GL", "GRL"),
    308 to IsoCountryCode("GD", "GRD"),
    312 to IsoCountryCode("GP", "GLP"),
    316 to IsoCountryCode("GU", "GUM"),
    320 to IsoCountryCode("GT", "GTM"),
    324 to IsoCountryCode("GN", "GIN"),
    328 to IsoCountryCode("GY", "GUY"),
    332 to IsoCountryCode("HT", "HTI"),
    334 to IsoCountryCode("HM", "HMD"),
    336 to IsoCountryCode("VA", "VAT"),
    340 to IsoCountryCode("HN", "HND"),
    344 to IsoCountryCode("HK", "HKG"),
    348 to IsoCountryCode("HU", "HUN"),
    352 to IsoCountryCode("IS", "ISL"),
    356 to IsoCountryCode("IN", "IND"),
    360 to IsoCountryCode("ID", "IDN"),
    364 to IsoCountryCode("IR", "IRN"),
    368 to IsoCountryCode("IQ", "IRQ"),
    372 to IsoCountryCode("IE", "IRL"),
    376 to IsoCountryCode("IL", "ISR"),
    380 to IsoCountryCode("IT", "ITA"),
    384 to IsoCountryCode("CI", "CIV"),
    388 to IsoCountryCode("JM", "JAM"),
    392 to IsoCountryCode("JP", "JPN"),
    398 to IsoCountryCode("KZ", "KAZ"),
    400 to IsoCountryCode("JO", "JOR"),
    404 to IsoCountryCode("KE", "KEN"),
    408 to IsoCountryCode("KP", "PRK"),
    410 to IsoCountryCode("KR", "KOR"),
    414 to IsoCountryCode("KW", "KWT"),
    417 to IsoCountryCode("KG", "KGZ"),
    418 to IsoCountryCode("LA", "LAO"),
    422 to IsoCountryCode("LB", "LBN"),
    426 to IsoCountryCode("LS", "LSO"),
    428 to IsoCountryCode("LV", "LVA"),
    430 to IsoCountryCode("LR", "LBR"),
    434 to IsoCountryCode("LY", "LBY"),
    438 to IsoCountryCode("LI", "LIE"),
    440 to IsoCountryCode("LT", "LTU"),
    442 to IsoCountryCode("LU", "LUX"),
    446 to IsoCountryCode("MO", "MAC"),
    450 to IsoCountryCode("MG", "MDG"),
    454 to IsoCountryCode("MW", "MWI"),
    458 to IsoCountryCode("MY", "MYS"),
    462 to IsoCountryCode("MV", "MDV"),
    466 to IsoCountryCode("ML", "MLI"),
    470 to IsoCountryCode("MT", "MLT"),
    474 to IsoCountryCode("MQ", "MTQ"),
    478 to IsoCountryCode("MR", "MRT"),
    480 to IsoCountryCode("MU", "MUS"),
    484 to IsoCountryCode("MX", "MEX"),
    492 to IsoCountryCode("MC", "MCO"),
    496 to IsoCountryCode("MN", "MNG"),
    498 to IsoCountryCode("MD", "MDA"),
    499 to IsoCountryCode("ME", "MNE"),
    500 to IsoCountryCode("MS", "MSR"),
    504 to IsoCountryCode("MA", "MAR"),
    508 to IsoCountryCode("MZ", "MOZ"),
    512 to IsoCountryCode("OM", "OMN"),
    516 to IsoCountryCode("NA", "NAM"),
    520 to IsoCountryCode("NR", "NRU"),
    524 to IsoCountryCode("NP", "NPL"),
    528 to IsoCountryCode("NL", "NLD"),
    531 to IsoCountryCode("CW", "CUW"),
    533 to IsoCountryCode("AW", "ABW"),
    534 to IsoCountryCode("SX", "SXM"),
    535 to IsoCountryCode("BQ", "BES"),
    540 to IsoCountryCode("NC", "NCL"),
    548 to IsoCountryCode("VU", "VUT"),
    554 to IsoCountryCode("NZ", "NZL"),
    558 to IsoCountryCode("NI", "NIC"),
    562 to IsoCountryCode("NE", "NER"),
    566 to IsoCountryCode("NG", "NGA"),
    570 to IsoCountryCode("NU", "NIU"),
    574 to IsoCountryCode("NF", "NFK"),
    578 to IsoCountryCode("NO", "NOR"),
    580 to IsoCountryCode("MP", "MNP"),
    581 to IsoCountryCode("UM", "UMI"),
    583 to IsoCountryCode("FM", "FSM"),
    584 to IsoCountryCode("MH", "MHL"),
    585 to IsoCountryCode("PW", "PLW"),
    586 to IsoCountryCode("PK", "PAK"),
    591 to IsoCountryCode("PA", "PAN"),
    598 to IsoCountryCode("PG", "PNG"),
    600 to IsoCountryCode("PY", "PRY"),
    604 to IsoCountryCode("PE", "PER"),
    608 to IsoCountryCode("PH", "PHL"),
    612 to IsoCountryCode("PN", "PCN"),
    616 to IsoCountryCode("PL", "POL"),
    620 to IsoCountryCode("PT", "PRT"),
    624 to IsoCountryCode("GW", "GNB"),
    626 to IsoCountryCode("TL", "TLS"),
    630 to IsoCountryCode("PR", "PRI"),
    634 to IsoCountryCode("QA", "QAT"),
    638 to IsoCountryCode("RE", "REU"),
    642 to IsoCountryCode("RO", "ROU"),
    643 to IsoCountryCode("RU", "RUS"),
    646 to IsoCountryCode("RW", "RWA"),
    652 to IsoCountryCode("BL", "BLM"),
    654 to IsoCountryCode("SH", "SHN"),
    659 to IsoCountryCode("KN", "KNA"),
    660 to IsoCountryCode("AI", "AIA"),
    662 to IsoCountryCode("LC", "LCA"),
    663 to IsoCountryCode("MF", "MAF"),
    666 to IsoCountryCode("PM", "SPM"),
    670 to IsoCountryCode("VC", "VCT"),
    674 to IsoCountryCode("SM", "SMR"),
    678 to IsoCountryCode("ST", "STP"),
    682 to IsoCountryCode("SA", "SAU"),
    686 to IsoCountryCode("SN", "SEN"),
    688 to IsoCountryCode("RS", "SRB"),
    690 to IsoCountryCode("SC", "SYC"),
    694 to IsoCountryCode("SL", "SLE"),
    702 to IsoCountryCode("SG", "SGP"),
    703 to IsoCountryCode("SK", "SVK"),
    704 to IsoCountryCode("VN", "VNM"),
    705 to IsoCountryCode("SI", "SVN"),
    706 to IsoCountryCode("SO", "SOM"),
    710 to IsoCountryCode("ZA", "ZAF"),
    716 to IsoCountryCode("ZW", "ZWE"),
    724 to IsoCountryCode("ES", "ESP"),
    728 to IsoCountryCode("SS", "SSD"),
    729 to IsoCountryCode("SD", "SDN"),
    732 to IsoCountryCode("EH", "ESH"),
    740 to IsoCountryCode("SR", "SUR"),
    744 to IsoCountryCode("SJ", "SJM"),
    748 to IsoCountryCode("SZ", "SWZ"),
    752 to IsoCountryCode("SE", "SWE"),
    756 to IsoCountryCode("CH", "CHE"),
    760 to IsoCountryCode("SY", "SYR"),
    762 to IsoCountryCode("TJ", "TJK"),
    764 to IsoCountryCode("TH", "THA"),
    768 to IsoCountryCode("TG", "TGO"),
    772 to IsoCountryCode("TK", "TKL"),
    776 to IsoCountryCode("TO", "TON"),
    780 to IsoCountryCode("TT", "TTO"),
    784 to IsoCountryCode("AE", "ARE"),
    788 to IsoCountryCode("TN", "TUN"),
    792 to IsoCountryCode("TR", "TUR"),
    795 to IsoCountryCode("TM", "TKM"),
    796 to IsoCountryCode("TC", "TCA"),
    798 to IsoCountryCode("TV", "TUV"),
    800 to IsoCountryCode("UG", "UGA"),
    804 to IsoCountryCode("UA", "UKR"),
    807 to IsoCountryCode("MK", "MKD"),
    818 to IsoCountryCode("EG", "EGY"),
    826 to IsoCountryCode("GB", "GBR"),
    831 to IsoCountryCode("GG", "GGY"),
    832 to IsoCountryCode("JE", "JEY"),
    833 to IsoCountryCode("IM", "IMN"),
    834 to IsoCountryCode("TZ", "TZA"),
    840 to IsoCountryCode("US", "USA"),
    850 to IsoCountryCode("VI", "VIR"),
    854 to IsoCountryCode("BF", "BFA"),
    858 to IsoCountryCode("UY", "URY"),
    860 to IsoCountryCode("UZ", "UZB"),
    862 to IsoCountryCode("VE", "VEN"),
    876 to IsoCountryCode("WF", "WLF"),
    882 to IsoCountryCode("WS", "WSM"),
    887 to IsoCountryCode("YE", "YEM"),
    894 to IsoCountryCode("ZM", "ZMB"),
    983 to IsoCountryCode("XK", "XKX"),
)

internal fun matchesCountrySearch(
    displayName: String,
    isoNumeric: Int,
    query: String
): Boolean {
    val trimmed = query.trim()
    if (trimmed.isBlank()) return true
    if (displayName.contains(trimmed, ignoreCase = true)) return true

    val code = IsoCountryCodesByNumeric[isoNumeric]
    val normalized = trimmed.uppercase(Locale.ROOT)
    val numeric = isoNumeric.toString()
    val numericPadded = numeric.padStart(3, '0')

    return normalized == numeric ||
        normalized == numericPadded ||
        normalized == code?.alpha2 ||
        normalized == code?.alpha3
}
